// <auto-generated />
namespace NoviKunstUitleen.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class DeletedStudentsandStaffmemberModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeletedStudentsandStaffmemberModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202004290622568_Deleted Students and Staffmember Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
